parameters:
    database_host: localhost
    database_port: '5432'
    database_name: LoginSymfony
    database_user: postgres
    database_password: postgres
    mailer_transport: null
    mailer_host: null
    mailer_user: null
    mailer_password: null
    secret: f1f7897e2ccea391664c93010cf3d72c7
    database_driver: pdo_pgsql
    database_path: null
