acme_security:
    resource: "@AcmeSecurityBundle/Resources/config/routing.yml"
    prefix:   /

mtd_registro:
    resource: "@MTDRegistroBundle/Resources/config/routing.yml"
    prefix:   /

mtd_login:
    resource: "@MTDLoginBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

